// types.js
export const FETCH_CHARACTERS_REQUEST = 'FETCH_CHARACTERS_REQUEST';
export const FETCH_CHARACTERS_SUCCESS = 'FETCH_CHARACTERS_SUCCESS';
export const FETCH_CHARACTERS_FAILURE = 'FETCH_CHARACTERS_FAILURE';
export const FETCH_SEARCH_BY_ID = 'FETCH_SEARCH_BY_ID';
export const FETCH_RESET = "FETCH_RESET";
export const GET_SPECIES = "GET_SPECIES";

//filtros

export const FETCH_FILTER_BY_GENRE = "FETCH_FILTER_BY_GENRE";
export const FETCH_FILTER_BY_SPECIES = "FETCH_FILTER_BY_SPECIES";
export const FETCH_FILTER_BY_STATE = "FETCH_FILTER_BY_STATE";

//like

export const ADD_LIKE= "ADD_LIKE";
export const DELETE_LIKE = "DELETE_LIKE";

